# -*- coding: utf-8 -*-
bwb_user_data_keys = [
    "connects_mbr_id",
    "email",
    "first_name",
    "last_name",
    "birthdate",
    "gender",
    "mdlive_id",
    "address1",
    "address2",
    "city",
    "state",
    "zip",
    "phone",
    "relationship_status",
    "employment_status",
    "job_title",
    "timezone",
]

bwb_user_response_keys = [
    "chief_complaint1",
    "chief_complaint2",
    "how_often_less_interest_in_things",
    "how_often_depressed",
    "how_often_nervous",
    "how_often_worry",
    "difficulty_in_keeping_drinking_limit",
    "felt_cut_down_drinking",
    "how_emotionally_doing",
    "how_physical_health",
    "people_support",
    "comfortable_in_managing_finances",
    "resources_to_manage",
    "number_of_days_missed_work",
    "number_of_days_less_productive",
]

bwb_organisation_keys = [
    "parent_code",
    "group_number",
    "benefit_package",
]

scc_user_data = {
    "memberId": "1234",
    "emailAddress": "shiva+04@fueled.com",
    "firstName": "shiva3",
    "lastName": "saxena",
    "dateOfBirth": "1991203",
    "gender": "M",
    "mdLiveMemberID": "4321",
    "addressLine1": "111 Est Road",
    "addressLine2": "222 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "11111",
    "phoneNumberAreaCode": "929",
    "phoneNumberCentralOfficeCode": "222",
    "phoneNumberExchange": "2222",
    "relationshipStatus": "1",
    "employmentStatus": "FT",
    "jobTitle": "TECH",
}

scc_user_response_data = {
    "primaryPresentingProblem": "AX",
    "secondaryPresentingProblem": "ST",
    "depressionScreenerQuestion3A": "1",
    "depressionScreenerQuestion3B": "2",
    "anxietyScreenerQuestion5A": "3",
    "anxietyScreenerQuestion5B": "1",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "3",
    "wellbeingDomainQuestion9": "1",
    "wellbeingDomainQuestion10": "1",
    "wellbeingDomainQuestion11": "2",
    "wellbeingDomainQuestion12": "3",
    "outcomesESDQuestion1": "3",
    "outcomesESDQuestion2": "3",
}

scc_organisation_data = {
    "parentCode": "COT",
    "groupNumber": "123",
    "benefitPackage": "demo",
}


# Different cases of SCC data
scc_normal_data = {
    "memberId": "1234",
    "emailAddress": "shiva+08@fueled.com",
    "mdLiveMemberID": "888",
    "firstName": "shiva8",
    "lastName": "saxena8",
    "dateOfBirth": "1991208",
    "gender": "M",
    "addressLine1": "888 Est Road",
    "addressLine2": "888 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "88888",
    "phoneNumberAreaCode": "929",
    "phoneNumberCentralOfficeCode": "888",
    "phoneNumberExchange": "8888",
    "parentCode": "COT",
    "groupNumber": "demo",
    "benefitPackage": "demo",
    "relationshipStatus": "D",
    "employmentStatus": "RE",
    "jobTitle": "TECH",
    "primaryPresentingProblem": "AX",
    "secondaryPresentingProblem": "GR",
    "depressionScreenerQuestion3A": "1",
    "depressionScreenerQuestion3B": "2",
    "anxietyScreenerQuestion5A": "3",
    "anxietyScreenerQuestion5B": "1",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "2",
    "wellbeingDomainQuestion9": "3",
    "wellbeingDomainQuestion10": "4",
    "wellbeingDomainQuestion11": "2",
    "wellbeingDomainQuestion12": "3",
    "outcomesESDQuestion1": "20",
    "outcomesESDQuestion2": "15",
}

bwb_normal_data = {
    "connects_mbr_id": "1234",
    "mdlive_id": "888",
    "email": "shiva+08@fueled.com",
    "first_name": "shiva8",
    "last_name": "saxena8",
    "birthdate": "1999-12-08",
    "gender": "M",
    "address1": "888 Est Road",
    "address2": "888 Wst Lane",
    "city": "Sunset",
    "state": "FL",
    "zip": "88888",
    "parent_code": "COT",
    "group_number": "demo",
    "benefit_package": "demo",
    "relationship_status": "Divorced",
    "employment_status": "Retired",
    "job_title": "Technical",
    "chief_complaint1": "Anxiety",
    "chief_complaint2": "Grief or Loss",
    "how_often_less_interest_in_things": "3",
    "how_often_depressed": "2",
    "how_often_nervous": "1",
    "how_often_worry": "3",
    "difficulty_in_keeping_drinking_limit": False,
    "felt_cut_down_drinking": True,
    "how_emotionally_doing": "2",
    "how_physical_health": "3",
    "people_support": "4",
    "comfortable_in_managing_finances": "2",
    "resources_to_manage": "3",
    "number_of_days_missed_work": 20,
    "number_of_days_less_productive": 15,
    "phone": "+19298888888",
}

scc_lower_bound_data = {
    "memberId": "1234",
    "emailAddress": "shiva+08@fueled.com",
    "mdLiveMemberID": "888",
    "firstName": "shiva8",
    "lastName": "saxena8",
    "dateOfBirth": "1991208",
    "gender": "M",
    "addressLine1": "888 Est Road",
    "addressLine2": "888 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "88888",
    "phoneNumberAreaCode": "929",
    "phoneNumberCentralOfficeCode": "888",
    "phoneNumberExchange": "8888",
    "parentCode": "COT",
    "groupNumber": "demo",
    "benefitPackage": "demo",
    "relationshipStatus": "1",
    "employmentStatus": "FT",
    "jobTitle": "EXEC",
    "primaryPresentingProblem": "EC",
    "secondaryPresentingProblem": "AX",
    "depressionScreenerQuestion3A": "0",
    "depressionScreenerQuestion3B": "0",
    "anxietyScreenerQuestion5A": "0",
    "anxietyScreenerQuestion5B": "0",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "N",
    "wellbeingDomainQuestion8": "1",
    "wellbeingDomainQuestion9": "1",
    "wellbeingDomainQuestion10": "1",
    "wellbeingDomainQuestion11": "1",
    "wellbeingDomainQuestion12": "1",
    "outcomesESDQuestion1": "CCD",
    "outcomesESDQuestion2": "CCD",
}

bwb_lower_bound_data = {
    "connects_mbr_id": "1234",
    "mdlive_id": "888",
    "email": "shiva+08@fueled.com",
    "first_name": "shiva8",
    "last_name": "saxena8",
    "birthdate": "1999-12-08",
    "gender": "M",
    "address1": "888 Est Road",
    "address2": "888 Wst Lane",
    "city": "Sunset",
    "state": "FL",
    "zip": "88888",
    "parent_code": "COT",
    "group_number": "demo",
    "benefit_package": "demo",
    "relationship_status": "Never Married",
    "employment_status": "Full Time",
    "job_title": "Executive/Manager",
    "chief_complaint1": "Stress",
    "chief_complaint2": "Anxiety",
    "how_often_less_interest_in_things": "4",
    "how_often_depressed": "4",
    "how_often_nervous": "4",
    "how_often_worry": "4",
    "difficulty_in_keeping_drinking_limit": False,
    "felt_cut_down_drinking": False,
    "how_emotionally_doing": "1",
    "how_physical_health": "1",
    "people_support": "1",
    "comfortable_in_managing_finances": "1",
    "resources_to_manage": "1",
    "number_of_days_missed_work": None,
    "number_of_days_less_productive": None,
    "phone": "+19298888888",
}

scc_upper_bound_data = {
    "memberId": "1234",
    "emailAddress": "shiva+08@fueled.com",
    "mdLiveMemberID": "888",
    "firstName": "shiva8",
    "lastName": "saxena8",
    "dateOfBirth": "1991208",
    "gender": "M",
    "addressLine1": "888 Est Road",
    "addressLine2": "888 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "88888",
    "phoneNumberAreaCode": "929",
    "phoneNumberCentralOfficeCode": "888",
    "phoneNumberExchange": "8888",
    "parentCode": "COT",
    "groupNumber": "demo",
    "benefitPackage": "demo",
    "relationshipStatus": "N",
    "employmentStatus": "OT",
    "jobTitle": "DATA",
    "primaryPresentingProblem": "DE",
    "secondaryPresentingProblem": "SU",
    "depressionScreenerQuestion3A": "N",
    "depressionScreenerQuestion3B": "N",
    "anxietyScreenerQuestion5A": "N",
    "anxietyScreenerQuestion5B": "N",
    "substanceUseQuestion7A": "Y",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "5",
    "wellbeingDomainQuestion9": "5",
    "wellbeingDomainQuestion10": "5",
    "wellbeingDomainQuestion11": "5",
    "wellbeingDomainQuestion12": "5",
    "outcomesESDQuestion1": "UNE",
    "outcomesESDQuestion2": "NAP",
}

bwb_upper_bound_data = {
    "connects_mbr_id": "1234",
    "mdlive_id": "888",
    "email": "shiva+08@fueled.com",
    "first_name": "shiva8",
    "last_name": "saxena8",
    "birthdate": "1999-12-08",
    "gender": "M",
    "address1": "888 Est Road",
    "address2": "888 Wst Lane",
    "city": "Sunset",
    "state": "FL",
    "zip": "88888",
    "parent_code": "COT",
    "group_number": "demo",
    "benefit_package": "demo",
    "relationship_status": None,
    "employment_status": None,
    "job_title": None,
    "chief_complaint1": "Stress",
    "chief_complaint2": "Alcohol or Drug use",
    "how_often_less_interest_in_things": None,
    "how_often_depressed": None,
    "how_often_nervous": None,
    "how_often_worry": None,
    "difficulty_in_keeping_drinking_limit": True,
    "felt_cut_down_drinking": True,
    "how_emotionally_doing": "5",
    "how_physical_health": "5",
    "people_support": "5",
    "comfortable_in_managing_finances": "5",
    "resources_to_manage": "5",
    "number_of_days_missed_work": None,
    "number_of_days_less_productive": None,
    "phone": "+19298888888",
}

scc_partial_data = {
    "relationshipStatus": "1",
    "employmentStatus": "FT",
    "jobTitle": "TECH",
    "primaryPresentingProblem": "AX",
    "secondaryPresentingProblem": None,
    "depressionScreenerQuestion3A": "1",
    "depressionScreenerQuestion3B": "2",
    "anxietyScreenerQuestion5A": None,
    "anxietyScreenerQuestion5B": "0",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "2",
    "wellbeingDomainQuestion9": None,
    "wellbeingDomainQuestion10": None,
    "wellbeingDomainQuestion11": "2",
    "wellbeingDomainQuestion12": "3",
    "outcomesESDQuestion1": "10",
    "outcomesESDQuestion2": "1",
}

bwb_partial_data = {
    "relationship_status": "Never Married",
    "employment_status": "Full Time",
    "job_title": "Technical",
    "chief_complaint1": "Anxiety",
    "chief_complaint2": None,
    "how_often_less_interest_in_things": "3",
    "how_often_depressed": "2",
    "how_often_nervous": None,
    "how_often_worry": "4",
    "difficulty_in_keeping_drinking_limit": False,
    "felt_cut_down_drinking": True,
    "how_emotionally_doing": "2",
    "how_physical_health": None,
    "people_support": None,
    "comfortable_in_managing_finances": "2",
    "resources_to_manage": "3",
    "number_of_days_missed_work": 10,
    "number_of_days_less_productive": 1,
}

scc_test_data_invalid_dob = {
    "memberId": "1234",
    "emailAddress": "shiva+08@fueled.com",
    "mdLiveMemberID": "888",
    "firstName": "shiva8",
    "lastName": "saxena8",
    "dateOfBirth": "9991208",
    "gender": "M",
    "addressLine1": "888 Est Road",
    "addressLine2": "888 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "88888",
    "phoneNumberAreaCode": "929",
    "phoneNumberCentralOfficeCode": "888",
    "phoneNumberExchange": "8888",
    "parentCode": "COT",
    "groupNumber": "demo",
    "benefitPackage": "demo",
    "relationshipStatus": "1",
    "employmentStatus": "FT",
    "jobTitle": "TECH",
    "primaryPresentingProblem": "AX",
    "secondaryPresentingProblem": "ST",
    "depressionScreenerQuestion3A": "1",
    "depressionScreenerQuestion3B": "2",
    "anxietyScreenerQuestion5A": "3",
    "anxietyScreenerQuestion5B": "0",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "2",
    "wellbeingDomainQuestion9": "1",
    "wellbeingDomainQuestion10": "1",
    "wellbeingDomainQuestion11": "2",
    "wellbeingDomainQuestion12": "3",
    "outcomesESDQuestion1": "10",
    "outcomesESDQuestion2": "1",
}

scc_test_data_invalid_phone = {
    "memberId": "1234",
    "emailAddress": "shiva+08@fueled.com",
    "mdLiveMemberID": "888",
    "firstName": "shiva8",
    "lastName": "saxena8",
    "dateOfBirth": "1991208",
    "gender": "M",
    "addressLine1": "888 Est Road",
    "addressLine2": "888 Wst Lane",
    "addressCity": "Sunset",
    "addressStateCode": "FL",
    "addressZipCode": "88888",
    "phoneNumberAreaCode": "000",
    "phoneNumberCentralOfficeCode": "000",
    "phoneNumberExchange": "0000",
    "parentCode": "COT",
    "groupNumber": "demo",
    "benefitPackage": "demo",
    "relationshipStatus": "1",
    "employmentStatus": "FT",
    "jobTitle": "TECH",
    "primaryPresentingProblem": "AX",
    "secondaryPresentingProblem": "ST",
    "depressionScreenerQuestion3A": "1",
    "depressionScreenerQuestion3B": "2",
    "anxietyScreenerQuestion5A": "3",
    "anxietyScreenerQuestion5B": "0",
    "substanceUseQuestion7A": "N",
    "substanceUseQuestion7B": "Y",
    "wellbeingDomainQuestion8": "2",
    "wellbeingDomainQuestion9": "1",
    "wellbeingDomainQuestion10": "1",
    "wellbeingDomainQuestion11": "2",
    "wellbeingDomainQuestion12": "3",
    "outcomesESDQuestion1": "10",
    "outcomesESDQuestion2": "1",
}
