# Generated by Django 2.1.7 on 2019-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20171024_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address1",
            field=models.CharField(max_length=200, null=True, verbose_name="Address1"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="Birth Date"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=50, null=True, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=10, null=True, verbose_name="Birth Date"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="user",
            name="relationship",
            field=models.CharField(
                max_length=15, null=True, verbose_name="Relationship"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(max_length=3, null=True, verbose_name="State"),
        ),
        migrations.AddField(
            model_name="user",
            name="zip",
            field=models.CharField(max_length=10, null=True, verbose_name="Zip"),
        ),
    ]
