# Generated by Django 2.1.7 on 2019-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20190305_1031"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="relationship",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip",
        ),
        migrations.AddField(
            model_name="user",
            name="mdlive_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="MDLive Id"),
        ),
    ]
