# Generated by Django 2.1.7 on 2019-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20190306_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cognito_access_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cognito Access Token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cognito_id_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cognito Id Token"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cognito_refresh_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cognito Refresh Token"
            ),
        ),
    ]
