# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-03-20 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        ("users", "0006_auto_20190313_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="organisations.Organisation",
            ),
        ),
    ]
