# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_organisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chief_complaint1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chief Complaint"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="chief_complaint2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chief Complaint"
            ),
        ),
    ]
