# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20190404_0706"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="appointment_state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="chief_complaint1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="chief_complaint2",
        ),
    ]
