# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20190410_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user email has been verified on cognito or not.",
                verbose_name="verified",
            ),
        ),
    ]
