# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-03 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address1",
            field=models.CharField(max_length=50, null=True, verbose_name="address1"),
        ),
        migrations.AddField(
            model_name="user",
            name="address2",
            field=models.CharField(max_length=50, null=True, verbose_name="address2"),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(null=True, verbose_name="birth date"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=35, null=True, verbose_name="city"),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Terminated", "Terminated"),
                    ("Medical Leave", "Medical Leave"),
                    ("Retired", "Retired"),
                    ("Disciplinary Leave", "Disciplinary Leave"),
                    ("Laid Off", "Laid Off"),
                    (
                        "Disability/Worker’s Compensation",
                        "Disability/Worker’s Compensation",
                    ),
                    ("Dependent", "Dependent"),
                ],
                max_length=50,
                null=True,
                verbose_name="employment status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30, null=True, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                max_length=2,
                null=True,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("Executive/Manager", "Executive/Manager"),
                    ("Professional", "Professional"),
                    ("Technical", "Technical"),
                    ("Sales", "Sales"),
                    ("Office/Clerical", "Office/Clerical"),
                    ("Craft Worker", "Craft Worker"),
                    ("Operative", "Operative"),
                    ("Laborer", "Laborer"),
                    ("Service Worker", "Service Worker"),
                    ("Dependent", "Dependent"),
                ],
                max_length=20,
                null=True,
                verbose_name="job title",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, null=True, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True, verbose_name="phone"),
        ),
        migrations.AddField(
            model_name="user",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("Never Married", "Never Married"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Cohabitating", "Cohabitating"),
                    ("Separated", "Separated"),
                    ("Widowed", "Widowed"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
                verbose_name="relationship status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DC", "District of Columbia"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("PR", "Puerto Rico"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=3,
                null=True,
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip",
            field=models.CharField(
                max_length=5,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(5),
                    django.core.validators.RegexValidator(
                        message="Enter a zip code in the format XXXXX",
                        regex="\\b\\d{5}\\b",
                    ),
                ],
                verbose_name="zip",
            ),
        ),
    ]
