# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20191003_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sent_to_campaign_monitor",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's data has been sent to campaign monitor or not.",
                verbose_name="sent to campaign monitor",
            ),
        ),
    ]
