# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_is_sent_to_campaign_monitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
