# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mdlive_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="MDLive Id"
            ),
        ),
    ]
