# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-18 11:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20191212_1100"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("pc", "PC"),
                            ("tablet", "Tablet"),
                            ("bot", "Bot"),
                        ],
                        max_length=7,
                        null=True,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "is_touch_capable",
                    models.NullBooleanField(verbose_name="is touch capable"),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="browser"
                    ),
                ),
                (
                    "browser_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="browser version",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="os"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="os version"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="device"
                    ),
                ),
                (
                    "device_brand",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="device brand",
                    ),
                ),
                (
                    "device_model",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="device model",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_agent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user agent",
                "verbose_name_plural": "user agents",
                "db_table": "user_agent",
                "ordering": ("-modified_at",),
            },
        ),
    ]
