# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20191219_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_failed_login_attempt_datetime",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Last Failed Login Attempt Datetime",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="num_of_failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of failed login attempts"
            ),
        ),
    ]
