# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20200109_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="source",
            field=models.CharField(
                choices=[("api", "api"), ("admin", "admin"), ("csv", "csv")],
                default="api",
                max_length=5,
                verbose_name="source",
            ),
        ),
    ]
