# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useragent",
            name="browser",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="browser"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="browser_version",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="browser version"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="device",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="device"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="device_brand",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="device brand"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="device_model",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="device model"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="os",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="os"
            ),
        ),
        migrations.AlterField(
            model_name="useragent",
            name="os_version",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="os version"
            ),
        ),
    ]
