# Generated by Django 3.1.6 on 2021-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_auto_20210216_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="connects_mbr_id",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Beacon's internal system ID"
            ),
        ),
    ]
