# Generated by Django 3.1.6 on 2021-03-04 09:44

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20210226_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="source_admin",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                blank=True, max_length=254, verbose_name="Source Admin Email"
            ),
        ),
    ]
