# -*- coding: utf-8 -*-
# Generated by Django 3.1.6 on 2021-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_source_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="source",
            field=models.CharField(
                choices=[
                    ("api", "api"),
                    ("admin", "admin"),
                    ("csv", "csv"),
                    ("scc", "scc"),
                ],
                default="api",
                max_length=5,
                verbose_name="source",
            ),
        ),
    ]
