# -*- coding: utf-8 -*-
# Generated by Django 3.1.6 on 2021-11-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20211111_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_to_scc_if_non_f2f",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user's data is to be send to SCC System or not, provided that the user hasn't opted for F2F appointment.",
                verbose_name="Send user data to SCC if user doesn't opt for F2F",
            ),
        ),
    ]
