# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("client_terminated", "Client terminated"),
                    ("eligibility_expired", "Eligibility expired"),
                    ("session_overuse", "Session overuse"),
                    ("duplicate_account", "Duplicate account"),
                    ("registered_in_error", "Registered in error"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="deactivation reason",
            ),
        ),
    ]
