# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-03-28 12:48

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address1",
            field=models.CharField(max_length=55, null=True, verbose_name="address1"),
        ),
        migrations.AlterField(
            model_name="user",
            name="address2",
            field=models.CharField(max_length=55, null=True, verbose_name="address2"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=30, null=True, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="user",
            name="connects_mbr_id",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Connects Member ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                db_index=True, max_length=50, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=35, null=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=60, null=True, verbose_name="last name"),
        ),
    ]
