# Generated by Django 3.2.11 on 2023-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_dfd_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer Not to say')], max_length=2, null=True, verbose_name='gender'),
        ),
    ]
