# -*- coding: utf-8 -*-
# Generated by Django 3.1.6 on 2021-11-22 11:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SccApiLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("request", models.JSONField()),
                ("response", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "successful"), ("failed", "failed")],
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scc_api_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "scc api log",
                "verbose_name_plural": "scc api logs",
                "db_table": "scc_api_log",
                "ordering": ["created_at"],
            },
        ),
    ]
