# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-03-22 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from beacon.scc.choices import REQUEST_DIRECTION_CHOICES


def add_default_direction(apps, schema_editor):
    """
    All older SCC API logs were created for the "outgoing" API requests from BWB to SCC
    system. However, adding default="outgoing" in the model definition for attribute
    `request_direction` would make the default value as "outgoing" even for all the
    future logs too, which would not be valid for future logs. Therefore, adding this
    custom operation to only apply default value on older objects.
    """
    scc_api_log_model = apps.get_model("scc", "SccApiLog")
    scc_api_logs_qs = scc_api_log_model.objects.all()
    scc_api_logs_qs.update(request_direction=REQUEST_DIRECTION_CHOICES.OUTGOING)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sccapilog",
            name="change_diff",
            field=models.JSONField(
                default=None,
                help_text="The updates made on existing data in BWB system.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sccapilog",
            name="request_direction",
            field=models.CharField(
                choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                help_text="The direction of API request with respect to BWB system.",
                max_length=15,
                null=True,
                verbose_name="Request Direction",
            ),
        ),
        migrations.AlterField(
            model_name="sccapilog",
            name="status",
            field=models.CharField(
                choices=[("successful", "Successful"), ("failed", "Failed")],
                max_length=15,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="sccapilog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scc_api_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(add_default_direction, migrations.RunPython.noop),
    ]
