# -*- coding: utf-8 -*-
EMOTIONAL_SUPPORT_FOR = "emotional_support_for"
APPOINTMENT_STATE = "appointment_state"
CHIEF_COMPLAINT1 = "chief_complaint1"
CHIEF_COMPLAINT2 = "chief_complaint2"
SELF_HARM = "self_harm"
SAFETY_SENSITIVE_POSITION = "safety_sensitive_position"
HOW_OFTEN_LESS_INTEREST_IN_THINGS = "how_often_less_interest_in_things"
HOW_OFTEN_DEPRESSED = "how_often_depressed"
HOW_OFTEN_NERVOUS = "how_often_nervous"
HOW_OFTEN_WORRY = "how_often_worry"
DIFFICULTY_IN_KEEPING_DRINKING_LIMIT = "difficulty_in_keeping_drinking_limit"
FELT_CUT_DOWN_DRINKING = "felt_cut_down_drinking"
HOW_EMOTIONALLY_DOING = "how_emotionally_doing"
HOW_PHYSICAL_HEALTH = "how_physical_health"
COMFORTABLE_IN_MANAGING_FINANCES = "comfortable_in_managing_finances"
PEOPLE_SUPPORT = "people_support"
RESOURCES_TO_MANAGE = "resources_to_manage"
NUMBER_OF_DAYS_LESS_PRODUCTIVE = "number_of_days_less_productive"
NUMBER_OF_DAYS_MISSED_WORK = "number_of_days_missed_work"
IS_EMPLOYEE = "is_employee"
RELATIONSHIP_WITH_EMPLOYEE = "relationship_with_employee"
EMPLOYEE_NAME = "employee_name"
EMPLOYEE_BIRTH_DATE = "employee_birth_date"
EMPLOYEE_ORGANISATION_ID = "employee_organisation_id"

APPOINTMENT_METHOD = "appointment_method"
F2F_CONFIRM = "f2f_confirm"
F2F_GENDER_PREFERENCE = "f2f_gender_preference"
F2F_COMFORTABLE_LANGUAGE = "f2f_comfortable_language"
F2F_PREFERRED_CONTACT = "f2f_preferred_contact"
F2F_PREFERRED_TIME = "f2f_preferred_time"
F2F_OKAY_TO_LEAVE_VOICEMAIL = "f2f_okay_to_leave_voicemail"
F2F_COUNSELOR_SEARCH_ADDRESS = "f2f_counselor_search_address"
F2F_ADDRESS1 = "f2f_address1"
F2F_ADDRESS2 = "f2f_address2"
F2F_ZIP = "f2f_zip"
F2F_CITY = "f2f_city"
F2F_STATE = "f2f_state"
F2F_COUNSELOR_NOTES = "f2f_counselor_notes"

USER_APPOINTMENT_ATTRIBUTE_CHOICES = [
    (APPOINTMENT_METHOD, APPOINTMENT_METHOD),
    (F2F_CONFIRM, F2F_CONFIRM),
    (F2F_GENDER_PREFERENCE, F2F_GENDER_PREFERENCE),
    (F2F_COMFORTABLE_LANGUAGE, F2F_COMFORTABLE_LANGUAGE),
    (F2F_PREFERRED_CONTACT, F2F_PREFERRED_CONTACT),
    (F2F_PREFERRED_TIME, F2F_PREFERRED_TIME),
    (F2F_OKAY_TO_LEAVE_VOICEMAIL, F2F_OKAY_TO_LEAVE_VOICEMAIL),
    (F2F_COUNSELOR_SEARCH_ADDRESS, F2F_COUNSELOR_SEARCH_ADDRESS),
    (F2F_ADDRESS1, F2F_ADDRESS1),
    (F2F_ADDRESS2, F2F_ADDRESS2),
    (F2F_ZIP, F2F_ZIP),
    (F2F_CITY, F2F_CITY),
    (F2F_STATE, F2F_STATE),
    (F2F_COUNSELOR_NOTES, F2F_COUNSELOR_NOTES),
]

USER_RESPONSE_ATTRIBUTE_CHOICES = [
    (EMOTIONAL_SUPPORT_FOR, EMOTIONAL_SUPPORT_FOR),
    (APPOINTMENT_STATE, APPOINTMENT_STATE),
    (CHIEF_COMPLAINT1, CHIEF_COMPLAINT1),
    (CHIEF_COMPLAINT2, CHIEF_COMPLAINT2),
    (SELF_HARM, SELF_HARM),
    (SAFETY_SENSITIVE_POSITION, SAFETY_SENSITIVE_POSITION),
    (HOW_OFTEN_LESS_INTEREST_IN_THINGS, HOW_OFTEN_LESS_INTEREST_IN_THINGS),
    (HOW_OFTEN_DEPRESSED, HOW_OFTEN_DEPRESSED),
    (HOW_OFTEN_NERVOUS, HOW_OFTEN_NERVOUS),
    (HOW_OFTEN_WORRY, HOW_OFTEN_WORRY),
    (DIFFICULTY_IN_KEEPING_DRINKING_LIMIT, DIFFICULTY_IN_KEEPING_DRINKING_LIMIT),
    (FELT_CUT_DOWN_DRINKING, FELT_CUT_DOWN_DRINKING),
    (HOW_EMOTIONALLY_DOING, HOW_EMOTIONALLY_DOING),
    (HOW_PHYSICAL_HEALTH, HOW_PHYSICAL_HEALTH),
    (COMFORTABLE_IN_MANAGING_FINANCES, COMFORTABLE_IN_MANAGING_FINANCES),
    (PEOPLE_SUPPORT, PEOPLE_SUPPORT),
    (RESOURCES_TO_MANAGE, RESOURCES_TO_MANAGE),
    (NUMBER_OF_DAYS_LESS_PRODUCTIVE, NUMBER_OF_DAYS_LESS_PRODUCTIVE),
    (NUMBER_OF_DAYS_MISSED_WORK, NUMBER_OF_DAYS_MISSED_WORK),
    (IS_EMPLOYEE, IS_EMPLOYEE),
    (RELATIONSHIP_WITH_EMPLOYEE, RELATIONSHIP_WITH_EMPLOYEE),
    (EMPLOYEE_NAME, EMPLOYEE_NAME),
    (EMPLOYEE_BIRTH_DATE, EMPLOYEE_BIRTH_DATE),
    (EMPLOYEE_ORGANISATION_ID, EMPLOYEE_ORGANISATION_ID),
]

# Chief Complaints
ANXIETY = "Anxiety"
DEPRESSION = "Depression"
FAMILY_ISSUES = "Family Issues"
GRIEF = "Grief or Loss"
RELATIONSHIP_ISSUES = "Relationship Issues"
STRESS = "Stress"
ALCOHOL = "Alcohol or Drug use"

F2F_HOME_ADDRESS = "home_address"
F2F_OTHER_ADDRESS = "other_address"
F2F_PHONE = "phone"
F2F_EMAIL = "email"
