# Generated by Django 2.1.7 on 2019-02-26 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fake_patient", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
                "db_table": "site_configuration",
            },
        ),
    ]
