# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20190226_0837"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCSVUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="open_for_upload", max_length=20, verbose_name="Status"
                    ),
                ),
                (
                    "csv_total_count",
                    models.IntegerField(default=0, verbose_name="Total Count"),
                ),
                (
                    "csv_completed_count",
                    models.IntegerField(default=0, verbose_name="Completed Count"),
                ),
            ],
            options={
                "verbose_name": "User CSV Upload",
                "db_table": "user_csv_upload",
            },
        ),
    ]
