# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-25 10:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_usercsvupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercsvupload",
            name="errors",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="usercsvupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("open_for_upload", "Open for Upload"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="open_for_upload",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
