# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20191025_1050"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercsvupload",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
