# Generated by Django 3.1.6 on 2021-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_siteconfiguration_mdlive_provider_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="fake_patient",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="usercsvupload",
            name="errors",
            field=models.JSONField(null=True),
        ),
    ]
