# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-11-29 10:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mdlive_id",
                    models.PositiveIntegerField(verbose_name="Mdlive message id"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user_message", "User Message"),
                            ("provider_message", "Provider Message"),
                        ],
                        default="user_message",
                        max_length=18,
                        verbose_name="Message Type",
                    ),
                ),
                ("subject", models.CharField(max_length=256, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Designates weather user have read the message or not!",
                        verbose_name="Is Read",
                    ),
                ),
                (
                    "replied_to_message_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Replied to mdlive message id",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "messages",
                "db_table": "message",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "mdlive_id",
                    models.PositiveIntegerField(verbose_name="Provider id on mdlive"),
                ),
                (
                    "fullname",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="prefix"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("System", "System"),
                        ],
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(max_length=50, verbose_name="Speciality"),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Image Url"
                    ),
                ),
            ],
            options={
                "verbose_name": "providers",
                "db_table": "provider",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_message",
                        to="mdlive.Message",
                    ),
                ),
                (
                    "message_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_messages",
                        to="mdlive.Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "users messages",
                "db_table": "user_message",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProviderMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_message",
                        to="mdlive.Message",
                    ),
                ),
                (
                    "message_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="mdlive.Provider",
                    ),
                ),
                (
                    "message_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "providers messages",
                "db_table": "provider_message",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="mdlive.Provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contacts",
                "db_table": "contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
