# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-06 08:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="photo_format",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="photo_in_binary_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="photo_url_absolute",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="specialities",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Specialities"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Speciality"
            ),
        ),
    ]
