# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0002_auto_20191206_0833"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_at"], "verbose_name": "contact"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-datetime"], "verbose_name": "message"},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"ordering": ["-created_at"], "verbose_name": "provider"},
        ),
        migrations.AlterModelOptions(
            name="providermessage",
            options={
                "ordering": ["id"],
                "verbose_name": "provider message",
                "verbose_name_plural": "providers messages",
            },
        ),
        migrations.AlterModelOptions(
            name="usermessage",
            options={
                "ordering": ["id"],
                "verbose_name": "user message",
                "verbose_name_plural": "users messages",
            },
        ),
    ]
