# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0003_auto_20191206_1556"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="mdlive_id",
            field=models.PositiveIntegerField(
                db_index=True, verbose_name="Mdlive message id"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="mdlive_id",
            field=models.PositiveIntegerField(
                db_index=True, verbose_name="Provider id on mdlive"
            ),
        ),
    ]
