# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-16 08:45

import uuid

import django.db.models.deletion
import uuid_upload_path.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdlive", "0004_auto_20191212_1100"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "document_name",
                    models.CharField(
                        max_length=30, verbose_name="document name with extension"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to=uuid_upload_path.storage.upload_to,
                        verbose_name="document",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        max_length=20, verbose_name="mime type of document"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("Behavioral", "Behavioral"),
                            ("Exam-Face2Face", "Exam-Face2Face"),
                            ("Patient Record", "Patient Record"),
                            ("Test Result", "Test Result"),
                            ("Wellness Panel Results", "Wellness Panel Results"),
                        ],
                        max_length=25,
                        verbose_name="record type",
                    ),
                ),
                (
                    "upload_to_mdlive_status",
                    models.BooleanField(
                        default=False, verbose_name="Uploaded to MDLive"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="mdlive.Message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user document",
                "db_table": "user_document",
                "ordering": ["-created_at"],
            },
        ),
    ]
