# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0007_auto_20200120_0819"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="mdlive_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Mdlive doc id"
            ),
        ),
    ]
