# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0008_userdocument_mdlive_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="extension",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Extension"
            ),
        ),
    ]
