# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-21 10:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdlive", "0009_userdocument_extension"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="document",
        ),
        migrations.RemoveField(
            model_name="userdocument",
            name="upload_to_mdlive_status",
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "mdlive_id",
                    models.PositiveIntegerField(
                        db_index=True,
                        null=True,
                        verbose_name="Mdlive appointment request id",
                    ),
                ),
                (
                    "provider_id",
                    models.PositiveIntegerField(
                        db_index=True, null=True, verbose_name="Provider id"
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        choices=[
                            ("morning", "morning"),
                            ("first available", "first available"),
                            ("afternoon", "afternoon"),
                            ("evening", "evening"),
                        ],
                        max_length=15,
                        verbose_name="preferred time",
                    ),
                ),
                (
                    "appointment_method",
                    models.CharField(
                        choices=[("phone", "phone"), ("video", "video")],
                        max_length=5,
                        verbose_name="appointment method",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="appointment date")),
                (
                    "chief_complaint",
                    models.CharField(
                        max_length=50, null=True, verbose_name="chief complaint"
                    ),
                ),
                (
                    "chief_complaint_comments",
                    models.CharField(
                        max_length=150,
                        null=True,
                        verbose_name="chief complaint comments",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15, null=True, verbose_name="contact number"
                    ),
                ),
                (
                    "appointment_request_state",
                    models.CharField(
                        max_length=2,
                        null=True,
                        verbose_name="appointment request state",
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="cancelled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment request",
                "db_table": "appointment_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
