# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-22 07:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0010_auto_20200121_1039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="message",
        ),
        migrations.CreateModel(
            name="MessageDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_documents",
                        to="mdlive.UserDocument",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_documents",
                        to="mdlive.Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "message document",
                "db_table": "message_document",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="documents",
            field=models.ManyToManyField(
                related_name="messages",
                through="mdlive.MessageDocument",
                to="mdlive.UserDocument",
            ),
        ),
    ]
