# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-23 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mdlive", "0011_auto_20200122_0750"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppointmentRequest",
            new_name="AppointmentSlotQuery",
        ),
        migrations.AlterModelOptions(
            name="appointmentslotquery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "appointment slot query",
                "verbose_name_plural": "appointment slot queries",
            },
        ),
        migrations.AlterModelTable(
            name="appointmentslotquery",
            table="appointment_slot_query",
        ),
    ]
