# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0012_auto_20200123_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_allowed",
            field=models.BooleanField(default=False, verbose_name="Reply Allowed"),
        ),
    ]
