# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdlive", "0013_message_reply_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdocument",
            name="document_name",
            field=models.CharField(
                max_length=200, verbose_name="document name with extension"
            ),
        ),
    ]
