# Generated by Django 2.1.7 on 2019-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="appointment_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "video"), ("phone", "phone")],
                max_length=5,
                null=True,
                verbose_name="Appointment Type",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="last_question_answered",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Last Answered Question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="mdlive_provider_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="MdLive selected provider id"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="selected_timeslot",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Selected Time Slot"
            ),
        ),
    ]
