# Generated by Django 2.1.7 on 2019-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0002_auto_20190228_1206"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="last_question_answered",
            new_name="last_answered_question",
        ),
    ]
