# Generated by Django 2.1.7 on 2019-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0003_auto_20190304_1135"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="appointment_type",
        ),
        migrations.AddField(
            model_name="answer",
            name="appointment_method",
            field=models.CharField(
                blank=True,
                choices=[("video", "video"), ("phone", "phone")],
                max_length=5,
                null=True,
                verbose_name="Appointment Method",
            ),
        ),
    ]
