# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0004_auto_20190308_0346"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="appointment_state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="chief_complaint1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="chief_complaint2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="comfortable_in_managing_finances",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="emotional_support_for",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="felt_cut_down_drinking",
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="how_often_depressed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="how_often_nervous",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="how_often_worry",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="number_of_days_less_productive",
            field=models.PositiveIntegerField(blank=True, max_length=365, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="number_of_days_missed_work",
            field=models.PositiveIntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="people_support",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="physical_health",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="resources_to_manage",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="used_drugs",
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
