# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-15 08:57

from django.db import migrations


def update_emotional_support_for_in_user_response(apps, schema_editor):
    user_response_model = apps.get_model("answers", "UserResponse")
    options_mapping = {
        "Myself": "Self",
        "MySelf": "Self",
        "My Partner": "Spouse",
        "A Co-Worker": "Other Adult",
        "A Dependent": "Child",
    }
    for user_res in user_response_model.objects.all():
        answer = next(
            (
                item
                for item in user_res.response
                if item["question"] == "Get emotional support for"
            ),
            None,
        )
        if answer is None:
            user_res.emotional_support_for = "Self"
        else:
            user_res.emotional_support_for = options_mapping[answer["answer"]]
            user_res.save()


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0007_auto_20190410_0923"),
        ("questionnaire", "0008_option_text_mapped_value"),
    ]

    operations = [
        migrations.RunPython(
            update_emotional_support_for_in_user_response, migrations.RunPython.noop
        )
    ]
