# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-25 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0009_auto_20190416_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="how_emotionally_doing",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="how_often_less_interest_in_things",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="how_physical_health",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="number_of_days_less_productive",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(30)],
            ),
        ),
    ]
