# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0011_remove_userresponse_physical_health"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userresponse",
            old_name="used_drugs",
            new_name="difficulty_in_keeping_drinking_limit",
        ),
    ]
