# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-08-31 17:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    user_response_model = apps.get_model("answers", "UserResponse")
    user_appointment_model = apps.get_model("answers", "UserAppointment")

    # Create UserQuestionViewed row for all User Responses
    # Migrate data from user response to user appointment
    for user_response in user_response_model.objects.all().order_by("created_at"):
        user_appointment_model.objects.create(
            user_response=user_response,
            mdlive_provider_id=user_response.mdlive_provider_id,
            selected_time_slot=user_response.selected_timeslot,
            appointment_method=user_response.appointment_method,
        )


def reverse_func(apps, schema_editor):
    user_appointment_model = apps.get_model("answers", "UserAppointment")
    user_appointment_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0013_auto_20190831_1702"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
