# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0015_auto_20190831_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="f2f_comfortable_language",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="F2F Comfortable Language",
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_confirm",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="F2F Confirm"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_counselor_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="F2F Counselor Notes"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_counselor_search_address",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="F2F Counselor Search Address",
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_gender_preference",
            field=models.CharField(
                blank=True,
                choices=[("M", "M"), ("F", "F")],
                max_length=15,
                null=True,
                verbose_name="F2F Gender Preference",
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_preferred_contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="F2F Preferred Contact",
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_preferred_time",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="F2F Preferred Time"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_preferred_time_agreement",
            field=models.NullBooleanField(verbose_name="F2F Preferred Time Agreement"),
        ),
    ]
