# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-02 18:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0016_auto_20190902_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="response",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
