# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0017_userappointment_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="f2f_address1",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="F2F Address1"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_address2",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="F2F Address2"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_city",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="F2F City"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_state",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="F2F State"
            ),
        ),
        migrations.AddField(
            model_name="userappointment",
            name="f2f_zip",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="F2F Zip"
            ),
        ),
    ]
