# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0019_auto_20190906_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="last_answered_question",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Last Answered Question",
            ),
        ),
    ]
