# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0021_auto_20190924_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="bwb_inquiry_id",
            field=models.CharField(
                max_length=40, null=True, verbose_name="BWB Inquiry Id"
            ),
        ),
    ]
