# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0022_userappointment_bwb_inquiry_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="request_type",
            field=models.CharField(default="Emotional", max_length=30, null=True),
        ),
    ]
