# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0021_organisation_template"),
        ("answers", "0024_userresponse_amtrek_safety_sensitive_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userresponse",
            old_name="amtrek_safety_sensitive_position",
            new_name="safety_sensitive_position",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="employee_birth_date",
            field=models.DateField(
                help_text="Designates employee DoB if user is dependent",
                null=True,
                verbose_name="employee date of birth",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="employee_name",
            field=models.CharField(
                blank=True,
                help_text="Designates employee full name if user is dependent",
                max_length=50,
                null=True,
                verbose_name="employee full name",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="employee_organisation",
            field=models.ForeignKey(
                blank=True,
                help_text="Designates the employee organisation if user is dependent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_responses",
                to="organisations.Organisation",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="is_employee",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="relationship_with_employee",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="self_harm",
            field=models.NullBooleanField(),
        ),
    ]
