# Generated by Django 3.1.6 on 2021-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0025_auto_20200303_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userappointment",
            name="f2f_okay_to_leave_voicemail",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="F2F Okay to Leave Voicemail"
            ),
        ),
        migrations.AlterField(
            model_name="userappointment",
            name="response",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="difficulty_in_keeping_drinking_limit",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="felt_cut_down_drinking",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="is_employee",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="response",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="safety_sensitive_position",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userresponse",
            name="self_harm",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
