# Generated by Django 3.1.6 on 2021-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0027_auto_20210301_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappointment",
            name="appointment_state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
