# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2021-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0028_userappointment_appointment_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="response_backup",
            field=models.JSONField(default=None, null=True),
        ),
    ]
