# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-02-10 14:16

from django.db import migrations


def remove_blank_chief_complaint2(apps, schema_editor):
    """
    In user answers, "" (blank) is not a valid value for `chief_complaint2` question. Users which were registered via
    Django admin panel would have blank saved in their answers for this question. So this migrations aims to replace
    those invalid blanks with `None`. This is done so that the validation fulfils criteria for SCC.
    """
    user_response_model = apps.get_model("answers", "UserResponse")
    user_response_qs = user_response_model.objects.all()
    for user_response in user_response_qs:
        if user_response.chief_complaint2 == "":
            user_response.chief_complaint2 = None
            user_response.save()


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0029_userresponse_response_backup"),
    ]

    operations = [
        migrations.RunPython(remove_blank_chief_complaint2, migrations.RunPython.noop),
    ]
