# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-03-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0030_auto_20220210_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userappointment",
            name="f2f_address1",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="F2F Address1"
            ),
        ),
        migrations.AlterField(
            model_name="userappointment",
            name="f2f_address2",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="F2F Address2"
            ),
        ),
        migrations.AlterField(
            model_name="userappointment",
            name="f2f_city",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="F2F City"
            ),
        ),
    ]
