# Generated by Django 2.1.7 on 2019-02-14 11:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=20, verbose_name="Choice text")),
            ],
            options={
                "verbose_name": "option",
                "verbose_name_plural": "options",
                "db_table": "option",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown"),
                            ("multiple_choice", "Multiple Choice"),
                            ("number", "Number"),
                            ("text", "Text"),
                            ("yes_no", "Yes/No"),
                            ("terminal", "Terminal"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Max. 300 characters allowed.",
                        max_length=300,
                        verbose_name="Question",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Placeholder Text",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user can skip this question.",
                        verbose_name="Is Required?",
                    ),
                ),
                (
                    "min_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum no. of characters or choices or number that the user must fill/select.",
                        null=True,
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum no. of characters or choices or number that the user can fill/select.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this question is published or not.",
                        verbose_name="Is Published?",
                    ),
                ),
                (
                    "is_start",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question is published or not.",
                        verbose_name="Is Starting Question?",
                    ),
                ),
                (
                    "next_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent",
                        to="questionnaire.Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "db_table": "question",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="option",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_option",
                to="questionnaire.Question",
            ),
        ),
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="questionnaire.Question",
            ),
        ),
    ]
