# Generated by Django 2.1.7 on 2019-02-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(max_length=30, verbose_name="Choice text"),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[
                    ("dropdown", "Dropdown"),
                    ("multiple_choice", "Multiple Choice"),
                    ("checkbox", "Checkbox"),
                    ("multiple_checkbox", "Multiple Checkbox"),
                    ("number", "Number"),
                    ("text", "Text"),
                    ("yes_no", "Yes/No"),
                    ("terminal", "Terminal"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
