# Generated by Django 2.1.7 on 2019-02-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_auto_20190220_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="previous_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_options",
                to="questionnaire.Question",
            ),
        ),
    ]
