# Generated by Django 2.1.7 on 2019-03-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_auto_20190225_1316"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["created_at"],
                "verbose_name": "option",
                "verbose_name_plural": "options",
            },
        ),
    ]
