# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_auto_20190304_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_field",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="AnswerField"
            ),
        ),
    ]
