# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_question_answer_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer_field",
        ),
        migrations.AddField(
            model_name="question",
            name="user_response_attribute",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emotional_support_for", "emotional_support_for"),
                    ("appointment_state", "appointment_state"),
                    ("chief_complaint1", "chief_complaint1"),
                    ("chief_complaint2", "chief_complaint2"),
                    ("how_often_depressed", "how_often_depressed"),
                    ("how_often_nervous", "how_often_nervous"),
                    ("how_often_worry", "how_often_worry"),
                    ("used_drugs", "used_drugs"),
                    ("felt_cut_down_drinking", "felt_cut_down_drinking"),
                    ("physical_health", "physical_health"),
                    (
                        "comfortable_in_managing_finances",
                        "comfortable_in_managing_finances",
                    ),
                    ("people_support", "people_support"),
                    ("resource_to_manage", "resource_to_manage"),
                    (
                        "number_of_days_less_productive",
                        "number_of_days_less_productive",
                    ),
                    ("number_of_days_missed_work", "number_of_days_missed_work"),
                ],
                max_length=50,
                null=True,
                verbose_name="User Response Attribute",
            ),
        ),
    ]
