# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_auto_20190410_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="text_mapped_value",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Text mapped value to be used",
            ),
        ),
    ]
