# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0012_auto_20190816_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_appointment_start",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is start question for appointment or not.",
                verbose_name="Is Appointment Starting Question?",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="leader_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follower_questions",
                to="questionnaire.Question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_start",
            field=models.BooleanField(
                default=False,
                help_text="Whether this question is start question or not.",
                verbose_name="Is Starting Question?",
            ),
        ),
    ]
