# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0016_auto_20190903_0616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(max_length=256, verbose_name="Choice text"),
        ),
    ]
