# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0018_auto_20190906_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subheading",
            field=models.CharField(
                blank=True,
                help_text="Max. 300 characters allowed.",
                max_length=300,
                null=True,
                verbose_name="Subheading",
            ),
        ),
    ]
