# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0021_auto_20190927_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="validate_number_length",
            field=models.BooleanField(
                default=False,
                help_text="Whether validate characters length for number on max_length/min_length or not. By default it validates on number instead of characters length",
                verbose_name="validate number length",
            ),
        ),
    ]
