# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0023_auto_20191113_0811"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="regex_error_message",
            field=models.CharField(
                help_text="Will be used if value is not getting matched with the regex",
                max_length=128,
                null=True,
                verbose_name="Regex Error Message",
            ),
        ),
    ]
