# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-02-06 08:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0018_remove_organisationhomepagenav_allow_search"),
        ("questionnaire", "0024_question_regex_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationNextQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "next_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_question_mapping",
                        to="questionnaire.Question",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_question_mapping",
                        to="questionnaire.Option",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_question_mapping",
                        to="organisations.Organisation",
                    ),
                ),
                (
                    "previous_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_question_mapping",
                        to="questionnaire.Question",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_question_mapping",
                        to="questionnaire.Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation next question",
                "db_table": "organisation_next_question",
                "ordering": ["created_at"],
            },
        ),
    ]
