# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-02-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0025_organisationnextquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationnextquestion",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_question_mapping",
                to="questionnaire.Question",
            ),
        ),
        migrations.AlterField(
            model_name="organisationnextquestion",
            name="previous_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_question_mapping",
                to="questionnaire.Question",
            ),
        ),
    ]
