# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0029_auto_20200303_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="backend_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dropdown", "Dropdown"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                    ("number", "Number"),
                    ("text", "Text"),
                    ("text_box", "Text Box"),
                    ("yes_no", "Yes/No"),
                    ("yes_no_options", "Yes/No Options"),
                    ("terminal", "Terminal"),
                    ("multiple_questions", "Multiple Questions"),
                    ("regex", "Regex"),
                    ("date", "Date"),
                    ("organisation", "Organisation"),
                    ("frontend", "Frontend"),
                ],
                max_length=20,
                null=True,
                verbose_name="Frontend Type mapped to",
            ),
        ),
    ]
