# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0030_question_backend_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatequestionmapping",
            name="next_question_service",
            field=models.CharField(
                blank=True,
                help_text="Service to get the next question instead of direct link",
                max_length=75,
                null=True,
                verbose_name="Service name",
            ),
        ),
        migrations.AlterField(
            model_name="templatequestionmapping",
            name="previous_question_service",
            field=models.CharField(
                blank=True,
                help_text="Service to get the previous question",
                max_length=75,
                null=True,
                verbose_name="Service name",
            ),
        ),
    ]
