# Generated by Django 3.1.6 on 2021-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0032_auto_20200304_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="user_response_attribute",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emotional_support_for", "emotional_support_for"),
                    ("appointment_state", "appointment_state"),
                    ("chief_complaint1", "chief_complaint1"),
                    ("chief_complaint2", "chief_complaint2"),
                    ("self_harm", "self_harm"),
                    ("safety_sensitive_position", "safety_sensitive_position"),
                    (
                        "how_often_less_interest_in_things",
                        "how_often_less_interest_in_things",
                    ),
                    ("how_often_depressed", "how_often_depressed"),
                    ("how_often_nervous", "how_often_nervous"),
                    ("how_often_worry", "how_often_worry"),
                    (
                        "difficulty_in_keeping_drinking_limit",
                        "difficulty_in_keeping_drinking_limit",
                    ),
                    ("felt_cut_down_drinking", "felt_cut_down_drinking"),
                    ("how_emotionally_doing", "how_emotionally_doing"),
                    ("how_physical_health", "how_physical_health"),
                    (
                        "comfortable_in_managing_finances",
                        "comfortable_in_managing_finances",
                    ),
                    ("people_support", "people_support"),
                    ("resources_to_manage", "resources_to_manage"),
                    (
                        "number_of_days_less_productive",
                        "number_of_days_less_productive",
                    ),
                    ("number_of_days_missed_work", "number_of_days_missed_work"),
                    ("is_employee", "is_employee"),
                    ("relationship_with_employee", "relationship_with_employee"),
                    ("employee_name", "employee_name"),
                    ("employee_birth_date", "employee_birth_date"),
                    ("employee_organisation_id", "employee_organisation_id"),
                ],
                max_length=50,
                null=True,
                verbose_name="User Response Attribute",
            ),
        ),
    ]
