# Generated by Django 3.1.6 on 2021-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0033_auto_20210211_0711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="frontend_meta_data",
            field=models.JSONField(
                blank=True,
                help_text="Extra meta data for rendering template on frontend",
                null=True,
                verbose_name="meta data",
            ),
        ),
    ]
