# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-08-16 13:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePagePhrase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("headline", models.CharField(max_length=256, verbose_name="headline")),
                (
                    "sub_headline",
                    models.CharField(max_length=350, verbose_name="sub-headline"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this message is visible on frontend or not!",
                        verbose_name="published",
                    ),
                ),
            ],
            options={
                "verbose_name": "home page phrase",
                "db_table": "home_page_phrase",
                "ordering": ["-created_at"],
            },
        ),
    ]
