# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-03-25 12:33

from django.db import migrations, models

import beacon.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0003_auto_20190322_0817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[beacon.users.validators.validate_phone_number],
                verbose_name="Phone",
            ),
        ),
    ]
