# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-03-25 15:10

import uuid_upload_path.storage
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0004_auto_20190325_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=uuid_upload_path.storage.upload_to,
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="logo_poi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5",
                editable=False,
                max_length=20,
                verbose_name="logo's point of interest",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="number_of_sessions",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Number of covered sessions per year",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="program_name",
            field=models.CharField(
                blank=True,
                help_text="e.g.: Beacon Wellbeing",
                max_length=50,
                null=True,
                verbose_name="Program Name",
            ),
        ),
    ]
