# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0006_homepagenav_organisationhomepagenav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagenav",
            name="url",
            field=models.CharField(max_length=250, verbose_name="url"),
        ),
    ]
