# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-09-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0007_auto_20190923_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagenav",
            name="nav_id",
        ),
    ]
