# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-11 12:20

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_organisation_show_international_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="location",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="organisations.Organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="domain",
            field=models.CharField(
                db_index=True,
                help_text="e.g.: client.mybeaconwellbeing.com",
                max_length=50,
                verbose_name="Domain or Host as unique identifier",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="username",
            field=models.CharField(
                help_text="Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=100,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
