# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-11 13:06

from django.db import migrations, models

import beacon.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0011_auto_20191011_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[beacon.users.validators.validate_phone_number],
                verbose_name="Phone",
            ),
        ),
    ]
