# -*- coding: utf-8 -*-
# Generated by Django 2.1.11 on 2019-10-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0012_auto_20191011_1306"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="parent_code",
            field=models.CharField(
                blank=True,
                help_text="This field is to match internal beacon server code. e.g. NGC, COT",
                max_length=50,
                null=True,
                verbose_name="Parent Code",
            ),
        ),
    ]
