# -*- coding: utf-8 -*-
# Generated by Django 2.2.6 on 2019-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_auto_20191129_0952"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepagenav",
            options={
                "ordering": ["is_emergency_nav", "created_at"],
                "verbose_name": "homepage nav",
            },
        ),
        migrations.AddField(
            model_name="homepagenav",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this nav should be treated as active.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="homepagenav",
            name="is_emergency_nav",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this nav is an emergency or not",
                verbose_name="is emergency",
            ),
        ),
        migrations.AddField(
            model_name="homepagenav",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this nav is available for all clients or not",
                verbose_name="is_global",
            ),
        ),
    ]
