# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0015_auto_20191209_1222"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationhomepagenav",
            name="allow_search",
            field=models.BooleanField(default=True, verbose_name="Allow Search"),
        ),
    ]
