# -*- coding: utf-8 -*-
# Generated by Django 2.2.9 on 2020-01-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0017_excludedorganisationhomepagenavsubcategories_homepagenavcategory_homepagenavsubcategory",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisationhomepagenav",
            name="allow_search",
        ),
    ]
