# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-02-14 11:25

from django.db import migrations, models

import beacon.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0018_remove_organisationhomepagenav_allow_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="safety_screen_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[beacon.users.validators.validate_phone_number],
                verbose_name="Safety screen contact number",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="safety_screen_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Safety screen url"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="show_safety_screen",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this organisation needs to show safety screen on Alcohol selection as chief complaint",
                verbose_name="Show safety screen",
            ),
        ),
    ]
