# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0029_auto_20200303_1226"),
        ("organisations", "0020_auto_20200225_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template of intake questions flow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisations",
                to="questionnaire.IntakeQuestionTemplate",
            ),
        ),
    ]
