# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0021_organisation_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="show_disclaimer",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Show Disclaimer"
            ),
        ),
    ]
