# -*- coding: utf-8 -*-
# Generated by Django 2.2.10 on 2020-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0022_organisation_show_disclaimer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="show_disclaimer",
            field=models.BooleanField(default=False, verbose_name="Show Disclaimer"),
        ),
    ]
