# Generated by Django 3.1.6 on 2021-02-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0023_auto_20200316_0929"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="introduction",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="Introduction"
            ),
        ),
    ]
