# Generated by Django 3.1.6 on 2021-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0024_organisation_introduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="is_no_of_sessions_hidden",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Is number of session hidden"
            ),
        ),
    ]
