# Generated by Django 3.1.6 on 2021-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0025_organisation_is_no_of_sessions_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="session_frequency",
            field=models.CharField(
                blank=True,
                help_text="Indicates if the number of sessions are per year, per quarter, etc.",
                max_length=120,
                verbose_name="Sessions frequency",
            ),
        ),
    ]
