# Generated by Django 3.1.6 on 2021-03-08 08:44

import uuid_upload_path.storage
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0026_organisation_session_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="glyph",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=uuid_upload_path.storage.upload_to,
                verbose_name="Client Glyph",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="glyph_poi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5",
                editable=False,
                max_length=20,
                verbose_name="Client glyph's point of interest",
            ),
        ),
    ]
