# Generated by Django 3.1.6 on 2021-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0027_auto_20210308_0844"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="glyph_height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Height of glyph in px",
                null=True,
                verbose_name="Height of the glyph",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="glyph_width",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Width of glyph in px",
                null=True,
                verbose_name="Width of the glyph",
            ),
        ),
    ]
