# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2021-12-23 17:19

from django.db import migrations, models


def add_initial_sort_order(apps, schema_editor):
    organisation_homepage_nav_model = apps.get_model(
        "organisations", "OrganisationHomepageNav"
    )
    order = 0
    for item in organisation_homepage_nav_model.objects.all():
        order += 1
        item.sort_order = order
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0029_auto_20211026_0644"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationhomepagenav",
            options={
                "ordering": ["sort_order", "created_at"],
                "verbose_name": "organisation homepage nav",
            },
        ),
        migrations.AddField(
            model_name="organisationhomepagenav",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Designates the position in the list of organisation's homepage navs.",
                verbose_name="Sort Order",
            ),
        ),
        migrations.RunPython(add_initial_sort_order, migrations.RunPython.noop),
    ]
