# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2022-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0030_auto_20211223_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagenav",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
    ]
