# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2022-01-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0031_homepagenav_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagenav",
            name="is_url_target_blank",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether URL opens in new browser tab (instead of same tab)",
                verbose_name="Open URL in new tab",
            ),
        ),
    ]
