# -*- coding: utf-8 -*-
# Generated by Django 3.2.8 on 2022-01-18 11:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0033_organisation_alternate_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="organisatio_search__5f0068_gin"
            ),
        ),
    ]
