# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0035_trigger_update_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="deactivation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent_org_deactivated", "Parent org deactivated"),
                    ("client_terminated", "Client terminated"),
                    ("duplicate_org", "Duplicate org"),
                    ("registered_in_error", "Registered in error"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="deactivation reason",
            ),
        ),
    ]
