# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-01-27 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0036_organisation_deactivation_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=256),
                blank=True,
                help_text="Alternate names of this organisation for search purposes. Use commas between names if entering multiple.",
                null=True,
                size=None,
            ),
        ),
    ]
