# -*- coding: utf-8 -*-
# Generated by Django 3.2.11 on 2022-03-28 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0037_alter_organisation_alternate_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="number_of_sessions",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(9999)],
                verbose_name="Number of covered sessions per year",
            ),
        ),
    ]
