# Generated by Django 3.2.11 on 2023-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0038_alter_organisation_number_of_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='Client Term Date'),
        ),
    ]
