# Generated by Django 3.2.11 on 2023-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0039_organisation_term_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='dfd_client',
            field=models.BooleanField(default=False),
        ),
    ]
