# Generated by Django 3.2.11 on 2023-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0040_organisation_dfd_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='dfd_client',
            field=models.BooleanField(default=False, verbose_name='dfd client'),
        ),
    ]
